name: smart_city
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  gap: ^3.0.1
  auto_route: ^9.2.2
  carousel_slider: ^5.0.0
  google_nav_bar: ^5.0.7
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  http: ^1.2.2
  http_parser: ^4.1.1
  injectable: ^2.5.0
  mime: ^1.0.6
  overlay_support: ^2.1.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  dio_http2_adapter: ^2.5.3
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  collection: ^1.19.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  hive_generator_plus: ^3.0.2
  injectable_generator: ^2.6.2
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7

dependency_overrides:
  collection: ^1.19.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/montserrat/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-Black.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/poppins/Poppins-Medium.ttf
          weight: 900


  #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#31511E" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  background_color_ios: "#31511E"